version: '3.1'
services:
  stats-server:
    build: stats-service
    image: stats-service-image
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - POSTGRES_USER=statsdb
      - POSTGRES_PASSWORD=stats
      - stats-service.url=http://stats-service:9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=statsdb
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - POSTGRES_USER=ewmdb
      - POSTGRES_PASSWORD=ewm

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewmdb
      - POSTGRES_PASSWORD=ewm